FROM golang:1.14 AS build

RUN apt-get update && apt-get install -y software-properties-common build-essential libssl-dev libsasl2-dev libzstd-dev

WORKDIR /root
RUN git clone https://github.com/edenhill/librdkafka.git
WORKDIR /root/librdkafka
RUN ./configure && make && make install

ADD . /go/src/github.com/kyungseopkim/goworkbed/kafka
WORKDIR /go/src/github.com/kyungseopkim/goworkbed/kafka
RUN go get
RUN go install -tags=static

WORKDIR /go/bin
RUN rm -rf /go/src/github.com/kyungseopkim
RUN rm -rf /root/librdkafka

ENTRYPOINT [ "/go/bin/kafka" ]
